#!/usr/bin/env bash
# Expects to be run in $ProjectFileDir$/elm-clients/dj-ops/

clear

set -x

ELM=src/DjOps.elm
JS=out/DjOps.js
MIN=../../kmkr/static/kmkr/DjOps.min.js

#if elm-make --yes ${ELM} --output=${JS} && minify ${JS} > ${MIN}
#if elm-make --debug --yes ${ELM} --output=${JS} && cat ${JS} > ${MIN}
if elm-make --yes ${ELM} --output=${JS} && cat ${JS} > ${MIN}
then
    sed -i "1i// Generated by Elm" ${JS}
    sed -i "1i// Generated by Elm" ${MIN}
fi

paplay /usr/share/sounds/ubuntu/stereo/dialog-information.ogg
