#!/usr/bin/env bash

# transpile.sh
# $1 is the Django app name
# $2 is the Elm filename (PyCharm $FileName$ macro)
# $3 is the Elm filename without extension (PyCharm's $FileNameWithoutExtension$ macro)

OUT=../static/$1/$3.js
if node_modules/.bin/elm-make --yes $2 --output=$OUT
then
    sed -i "1i// Generated by Elm" $OUT
fi
