# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensetransaction',
            unique_together=set([]),
        ),
    ]
