# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170429_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, help_text='The parent account for this account, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, to='books.Account'),
        ),
    ]
