# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_account_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payableinvoice',
            name='subject_to_1099',
            field=models.BooleanField(default='False', help_text='Check if this invoice is subject to 1099-MISC reporting requirements.'),
        ),
    ]
