# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 20:07
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_payableinvoice_subject_to_1099'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_verb', models.CharField(choices=[('FUNDS', 'Funds')], help_text="The type of link between the accounts. Subject acct 'verbs' object acct.", max_length=5)),
                ('obj_acct', models.ForeignKey(help_text='The object account in this link.', on_delete=django.db.models.deletion.PROTECT, related_name='obj_link_set', to='books.Account')),
                ('subj_acct', models.ForeignKey(help_text='The subject account in this link.', on_delete=django.db.models.deletion.PROTECT, related_name='subj_link_set', to='books.Account')),
            ],
            options={
                'ordering': ['subj_acct', 'link_verb', 'obj_acct'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the budget.', max_length=40)),
                ('begins', models.DateField(help_text='Date of first transfer.')),
                ('ends', models.DateField(help_text='Date of last transfer.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount to transfer.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('from_acct', models.ForeignKey(help_text='The acct FROM which funds will be transferred.', on_delete=django.db.models.deletion.PROTECT, related_name='from_budget_set', to='books.Account')),
                ('to_acct', models.ForeignKey(help_text='The acct TO which funds will be transferred.', on_delete=django.db.models.deletion.PROTECT, related_name='to_budget_set', to='books.Account')),
            ],
        ),
        migrations.RemoveField(
            model_name='accountgroup',
            name='accounts',
        ),
        migrations.AlterField(
            model_name='payableinvoice',
            name='subject_to_1099',
            field=models.BooleanField(default='False', help_text='Check if this invoice is subject to 1099-MISC reporting requirements.', verbose_name='1099'),
        ),
        migrations.DeleteModel(
            name='AccountGroup',
        ),
        migrations.AlterUniqueTogether(
            name='accountlink',
            unique_together=set([('subj_acct', 'link_verb', 'obj_acct')]),
        ),
    ]
