# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 21:34
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20170611_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField(help_text='Date of the transfer.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of the transfer.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('why', models.CharField(help_text='A short explanation of the transfer.', max_length=80)),
                ('from_acct', models.ForeignKey(help_text='The acct FROM which funds were transferred.', on_delete=django.db.models.deletion.PROTECT, related_name='from_xfer_set', to='books.Account')),
                ('to_acct', models.ForeignKey(help_text='The acct TO which funds were transferred.', on_delete=django.db.models.deletion.PROTECT, related_name='to_xfer_set', to='books.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The amount of each transfer.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='begins',
            field=models.DateField(help_text='Date of first monthly transfer.'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='ends',
            field=models.DateField(help_text='Date of last monthly transfer.'),
        ),
    ]
