# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20170613_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransfer',
            name='budget',
            field=models.ForeignKey(blank=True, default=None, help_text='The associated budget, if any. Normally blank for manual transfers.', null=True, on_delete=django.db.models.deletion.PROTECT, to='books.Budget'),
        ),
        migrations.AlterUniqueTogether(
            name='cashtransfer',
            unique_together=set([('from_acct', 'to_acct', 'when', 'why')]),
        ),
    ]
