# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_cashtransfer_frozen_in_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short name for the bank account.', max_length=40, unique=True)),
                ('description', models.TextField(help_text='A description of the bank account, the reason it exists, etc.', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField(help_text='The date on which the balance was recorded.')),
                ('balance', models.DecimalField(decimal_places=2, help_text='The dollar balance on the given date.', max_digits=8)),
                ('bank_account', models.ForeignKey(help_text='The account with this balance.', on_delete=django.db.models.deletion.PROTECT, to='books.BankAccount')),
            ],
        ),
    ]
