# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_bankaccount_bankaccountbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetarydonation',
            name='earmark',
            field=models.ForeignKey(blank=True, default=35, help_text='Specify a donation subaccount, when possible.', null=True, on_delete=django.db.models.deletion.PROTECT, to='books.Account'),
        ),
    ]
