# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20170616_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetarydonation',
            name='earmark',
            field=models.ForeignKey(default=35, help_text='Specify a donation subaccount, when possible.', on_delete=django.db.models.deletion.PROTECT, to='books.Account'),
        ),
    ]
