# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20170618_1327'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashtransfer',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='cashtransfer',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='cashtransfer',
            name='from_acct',
        ),
        migrations.RemoveField(
            model_name='cashtransfer',
            name='to_acct',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='account',
        ),
        migrations.AddField(
            model_name='budget',
            name='frozen_in_journal',
            field=models.BooleanField(default=False, help_text='If true, the journal entries for this transaction are frozen and will not be modified.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cash_account',
            field=models.OneToOneField(blank=True, help_text='The cash account used by this campaign.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_as_cash', to='books.Account'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='revenue_account',
            field=models.OneToOneField(blank=True, help_text='The revenue account used by this campaign.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_as_revenue', to='books.Account'),
        ),
        migrations.AddField(
            model_name='monetarydonation',
            name='campaign',
            field=models.ForeignKey(blank=True, default=None, help_text='This is a denormalized field and will be maintained by code.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Campaign'),
        ),
        migrations.DeleteModel(
            name='CashTransfer',
        ),
    ]
