# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 23:09
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20170619_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frozen_in_journal', models.BooleanField(default=False, help_text='If true, the journal entries for this transaction are frozen and will not be modified.')),
                ('when', models.DateField(help_text='Date of the transfer.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of the transfer.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('why', models.CharField(help_text='A short explanation of the transfer.', max_length=80)),
                ('from_acct', models.ForeignKey(help_text='The acct FROM which funds were transferred.', on_delete=django.db.models.deletion.PROTECT, related_name='from_xfer_set', to='books.Account')),
                ('to_acct', models.ForeignKey(help_text='The acct TO which funds were transferred.', on_delete=django.db.models.deletion.PROTECT, related_name='to_xfer_set', to='books.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cash_account',
            field=models.OneToOneField(default=1, help_text='The cash account used by this campaign.', on_delete=django.db.models.deletion.PROTECT, related_name='campaign_as_cash', to='books.Account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='revenue_account',
            field=models.OneToOneField(default=35, help_text='The revenue account used by this campaign.', on_delete=django.db.models.deletion.PROTECT, related_name='campaign_as_revenue', to='books.Account'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cashtransfer',
            unique_together=set([('from_acct', 'to_acct', 'when', 'why')]),
        ),
    ]
