# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20170619_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignnote',
            name='needs_attn',
            field=models.BooleanField(default=False, help_text='Check this to indicate that further action is required from some human.'),
        ),
        migrations.AddField(
            model_name='donationnote',
            name='needs_attn',
            field=models.BooleanField(default=False, help_text='Check this to indicate that further action is required from some human.'),
        ),
        migrations.AddField(
            model_name='entitynote',
            name='needs_attn',
            field=models.BooleanField(default=False, help_text='Check this to indicate that further action is required from some human.'),
        ),
        migrations.AddField(
            model_name='expenseclaimnote',
            name='needs_attn',
            field=models.BooleanField(default=False, help_text='Check this to indicate that further action is required from some human.'),
        ),
        migrations.AddField(
            model_name='expensetransactionnote',
            name='needs_attn',
            field=models.BooleanField(default=False, help_text='Check this to indicate that further action is required from some human.'),
        ),
        migrations.AddField(
            model_name='payableinvoicenote',
            name='needs_attn',
            field=models.BooleanField(default=False, help_text='Check this to indicate that further action is required from some human.'),
        ),
        migrations.AddField(
            model_name='receivableinvoicenote',
            name='needs_attn',
            field=models.BooleanField(default=False, help_text='Check this to indicate that further action is required from some human.'),
        ),
        migrations.AddField(
            model_name='salenote',
            name='needs_attn',
            field=models.BooleanField(default=False, help_text='Check this to indicate that further action is required from some human.'),
        ),
    ]
