# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20170622_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='unbalanced',
            field=models.BooleanField(default=False, help_text='Indicates that the entry is unbalanced. Human intervention required, if true.'),
        ),
    ]
