# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_journalentry_unbalanced'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='for_accts',
            field=models.ManyToManyField(blank=True, help_text='The account(s) ultimately funded by this budget.', to='books.Account'),
        ),
    ]
