# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_budget_for_accts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountlink',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accountlink',
            name='obj_acct',
        ),
        migrations.RemoveField(
            model_name='accountlink',
            name='subj_acct',
        ),
        migrations.DeleteModel(
            name='AccountLink',
        ),
    ]
