# Generated by Django 2.0.3 on 2018-04-23 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0018_auto_20170624_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='associated_entity',
            field=models.ForeignKey(blank=True, help_text='The entity which is associated with this account, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_entity', to='books.Entity'),
        ),
        migrations.AddField(
            model_name='account',
            name='associated_user',
            field=models.ForeignKey(blank=True, help_text='The person who is associated with this account, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
