# Generated by Django 2.0.3 on 2018-04-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20180422_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentrylineitem',
            name='description',
            field=models.CharField(blank=True, help_text='A brief description of this line item.', max_length=128),
        ),
    ]
