# Generated by Django 2.0.3 on 2018-05-06 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20180504_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountbalance',
            name='order_on_date',
            field=models.IntegerField(default=0, help_text='0 indicates end-of-day! Earlier entries must be negative.', validators=[django.core.validators.MaxValueValidator(0)]),
        ),
    ]
