# Generated by Django 2.0.3 on 2018-05-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_bankaccountbalance_order_on_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccountbalance',
            unique_together={('bank_account', 'when', 'order_on_date')},
        ),
    ]
