# Generated by Django 2.0.3 on 2018-05-10 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('books', '0024_auto_20180510_1300'), ('books', '0025_auto_20180510_1321')]

    dependencies = [
        ('books', '0023_auto_20180506_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, help_text='The total amount that needs to be collected in donations.', max_digits=7),
        ),
        migrations.AlterField(
            model_name='expenselineitem',
            name='account',
            field=models.ForeignKey(help_text="The account against which this line item is claimed, e.g. 'Wood Shop', '3D Printers'.", limit_choices_to=models.Q(models.Q(('category', 'X'), ('category', 'A'), _connector='OR'), models.Q(models.Q(('parent_id', 1), ('id', 1), _connector='OR'), _negated=True)), on_delete=django.db.models.deletion.CASCADE, to='books.Account'),
        ),
        migrations.RemoveField(
            model_name='account',
            name='associated_entity',
        ),
        migrations.RemoveField(
            model_name='account',
            name='associated_user',
        ),
        migrations.AddField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True, help_text='Uncheck when an account is no longer actively used.'),
        ),
    ]
