# Generated by Django 2.0.3 on 2018-06-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_auto_20180521_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashtransfer',
            options={'verbose_name': 'transfer'},
        ),
    ]
