# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-05 03:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0039_auto_20160927_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetransaction',
            name='recipient_acct',
            field=models.ForeignKey(blank=True, default=None, help_text='If payment was made to a user, speicfy them here.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User acct paid'),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='recipient_email',
            field=models.EmailField(blank=True, help_text='Sometimes useful in addition to name.', max_length=40, verbose_name='Optional email'),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='recipient_entity',
            field=models.ForeignKey(blank=True, default=None, help_text='If some outside person/org was paid, specify them here.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Entity', verbose_name='Entity acct paid'),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='recipient_name',
            field=models.CharField(blank=True, help_text="Name of person/org paid. Not req'd if an acct was linked, above.", max_length=40, verbose_name='Name paid'),
        ),
    ]
