# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-10 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0041_auto_20161009_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayableInvoiceLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='A brief description of this line item.', max_length=128)),
                ('delivery_date', models.DateField(help_text='The date on which this line item was delivered.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The dollar amount for this line item.', max_digits=6)),
                ('account', models.ForeignKey(help_text='The account associated with this line item.', on_delete=django.db.models.deletion.PROTECT, to='books.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceivableInvoiceLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='A brief description of this line item.', max_length=128)),
                ('delivery_date', models.DateField(help_text='The date on which this line item was delivered.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The dollar amount for this line item.', max_digits=6)),
                ('account', models.ForeignKey(help_text='The account associated with this line item.', on_delete=django.db.models.deletion.PROTECT, to='books.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='payableinvoice',
            name='account',
        ),
        migrations.RemoveField(
            model_name='receivableinvoice',
            name='account',
        ),
        migrations.AlterField(
            model_name='payableinvoice',
            name='description',
            field=models.TextField(help_text='Description of goods and/or services we received from them.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='receivableinvoice',
            name='description',
            field=models.TextField(help_text='Description of goods and/or services we delivered to them.', max_length=1024),
        ),
        migrations.AddField(
            model_name='receivableinvoicelineitem',
            name='inv',
            field=models.ForeignKey(blank=True, help_text='The receivable invoice on which this line item appears.', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.ReceivableInvoice'),
        ),
        migrations.AddField(
            model_name='payableinvoicelineitem',
            name='inv',
            field=models.ForeignKey(blank=True, help_text='The payable invoice on which this line item appears.', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.PayableInvoice'),
        ),
    ]
