# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-27 17:45
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0043_auto_20161018_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonetaryDonationReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the reward.', max_length=40)),
                ('cost_to_org', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The cost of this reward to the organization.', max_digits=6)),
                ('description', models.TextField(help_text='Description of the reward.', max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='monetarydonation',
            name='reward',
            field=models.ForeignKey(blank=True, default=None, help_text='The reward given to the donor, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, to='books.MonetaryDonationReward'),
        ),
    ]
