# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-28 18:39
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0044_auto_20161027_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short name of the campaign.', max_length=40)),
                ('is_active', models.BooleanField(default=True, help_text='Whether or not this campaign is currently being pursued.')),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='The total amount that needs to be collected in donations.', max_digits=6)),
                ('description', models.TextField(help_text='A description of the campaign and why people should donate to it.', max_length=1024)),
                ('account', models.ForeignKey(help_text='The account used by this campaign.', on_delete=django.db.models.deletion.PROTECT, to='books.Account')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Anything you want to say about the item on which this note appears.', max_length=2048)),
                ('is_public', models.BooleanField(default=False, help_text='Should this note be visible to the public as a campaign update?')),
                ('author', models.ForeignKey(blank=True, help_text='The user who wrote this note.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(help_text='The campaign to which this public update applies.', on_delete=django.db.models.deletion.CASCADE, to='books.Campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='monetarydonationreward',
            name='fair_mkt_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The value of this reward to the donor, for tax purposes.', max_digits=6),
        ),
        migrations.AddField(
            model_name='monetarydonationreward',
            name='min_donation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The minimum donation required to earn this reward.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='monetarydonationreward',
            name='cost_to_org',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The cost of this reward to Xerocraft.', max_digits=6),
        ),
    ]
