# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-06 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0046_journalentry_journalentrylineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetransaction',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='Automatically maintained by accounting commands. Do not modify.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.JournalEntry'),
        ),
        migrations.AddField(
            model_name='sale',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='Automatically maintained by accounting commands. Do not modify.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.JournalEntry'),
        ),
        migrations.AlterField(
            model_name='journalentrylineitem',
            name='account',
            field=models.ForeignKey(help_text='The account involved in this line item.', on_delete=django.db.models.deletion.PROTECT, to='books.Account'),
        ),
        migrations.AlterField(
            model_name='journalentrylineitem',
            name='journal_entry',
            field=models.ForeignKey(help_text='The journal entry that this line item is part of.', on_delete=django.db.models.deletion.CASCADE, to='books.JournalEntry'),
        ),
    ]
