# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-09 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0047_auto_20170106_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaim',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='Automatically maintained by accounting commands. Do not modify.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.JournalEntry'),
        ),
    ]
