# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-14 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0049_otheritemtype_revenue_acct'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='fee_payer',
            field=models.CharField(choices=[('N', 'N/A'), ('C', 'Customer'), ('U', 'Xerocraft')], default='U', help_text='Who paid the processing fee (if any)?', max_length=1),
        ),
    ]
