# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-18 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0051_auto_20170115_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['when']},
        ),
        migrations.RemoveField(
            model_name='expenseclaim',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='expensetransaction',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='payableinvoice',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='receivableinvoice',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='journal_entry',
        ),
    ]
