# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 18:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0052_auto_20170118_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselineitem',
            name='approved_by',
            field=models.ForeignKey(blank=True, default=None, help_text='Usually the shop/account manager. Leave blank if not yet approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
