# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0053_auto_20170124_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenselineitem',
            name='bought_from',
            field=models.ForeignKey(blank=True, default=None, help_text='Who was this purchased from (optional).', null=True, on_delete=django.db.models.deletion.PROTECT, to='books.Entity'),
        ),
        migrations.AddField(
            model_name='expenselineitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Any CHARITABLE discount applied to this purchase.', max_digits=6),
        ),
    ]
