# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0054_auto_20170124_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaim',
            name='frozen_in_journal',
            field=models.BooleanField(default=False, help_text='If true, the journal entries for this transaction are frozen and will not be modified.'),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='frozen_in_journal',
            field=models.BooleanField(default=False, help_text='If true, the journal entries for this transaction are frozen and will not be modified.'),
        ),
        migrations.AddField(
            model_name='payableinvoice',
            name='frozen_in_journal',
            field=models.BooleanField(default=False, help_text='If true, the journal entries for this transaction are frozen and will not be modified.'),
        ),
        migrations.AddField(
            model_name='receivableinvoice',
            name='frozen_in_journal',
            field=models.BooleanField(default=False, help_text='If true, the journal entries for this transaction are frozen and will not be modified.'),
        ),
        migrations.AddField(
            model_name='sale',
            name='frozen_in_journal',
            field=models.BooleanField(default=False, help_text='If true, the journal entries for this transaction are frozen and will not be modified.'),
        ),
    ]
