# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0056_auto_20170228_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name'], 'verbose_name': 'Non-Member Entity', 'verbose_name_plural': 'Non-Member Entities'},
        ),
        migrations.AddField(
            model_name='sale',
            name='send_receipt',
            field=models.BooleanField(default=False, help_text='(Re)send a DONATION receipt to the donor. Note: Will send at night.'),
        ),
    ]
