# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0057_auto_20170307_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivableinvoice',
            name='send_invoice',
            field=models.BooleanField(default=False, help_text='(Re)send the invoice via email. Note: Will be sent at night.'),
        ),
    ]
