# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0058_receivableinvoice_send_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetransaction',
            name='method_detail',
            field=models.CharField(blank=True, help_text='Optional detail specific to the payment method. Check# for check payments.', max_length=40, null=True),
        ),
        migrations.RunSQL(
            "update books_expensetransaction set method_detail=NULL where method_detail=''"
        )
    ]
