# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0059_auto_20170327_1220'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensetransaction',
            unique_together=set([('payment_method', 'method_detail')]),
        ),
    ]
