#!/usr/bin/env bash
# build.sh executes with working directory $ProjectFileDir$

set -x

pushd elm-clients/ops-calendar

ELM=src/OpsCalendar.elm
JS=out/OpsCalendar.js
MIN=../../tasks/static/tasks/OpsCalendar.min.js

if elm-make --yes ${ELM} --output=${JS} && minify --output ${MIN} ${JS}
then
    sed -i "1i// Generated by Elm" ${JS}
    sed -i "1i// Generated by Elm" ${MIN}
fi

beep
popd

