#!/usr/bin/env bash
# transpile.sh executes with working directory $ProjectFileDir$

set -x

pushd elm-clients/reception-kiosk

ELM=src/ReceptionKiosk.elm
JS=bin/ReceptionKiosk.js
MIN=../../members/static/members/ReceptionKiosk.min.js

if elm-make --yes ${ELM} --output=${JS} && minify --output ${MIN} ${JS}

then
    sed -i "1i// Generated by Elm" ${JS}
    sed -i "1i// Generated by Elm" ${MIN}
fi
beep
popd

