# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timepattern',
            name='person_in_class_template',
        ),
        migrations.RemoveField(
            model_name='timepattern',
            name='resource_in_class_tempate',
        ),
        migrations.AddField(
            model_name='personinclasstemplate',
            name='time_patterns',
            field=models.ManyToManyField(to='flock.TimePattern'),
        ),
        migrations.AddField(
            model_name='resourceinclasstemplate',
            name='time_patterns',
            field=models.ManyToManyField(to='flock.TimePattern'),
        ),
        migrations.AddField(
            model_name='timepattern',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flock.PersonInClassTemplate'),
        ),
        migrations.AddField(
            model_name='timepattern',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flock.ResourceInClassTemplate'),
        ),
    ]
