# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='seats_still_available',
        ),
        migrations.AddField(
            model_name='person',
            name='rest_time',
            field=models.IntegerField(default=1, help_text='Minimum days between meetings.'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='asked_assistants',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='asked_for_resources',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='asked_instructor',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='asked_students',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='invoiced_students',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
