# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0003_auto_20170409_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personinclasstemplate',
            name='time_patterns',
        ),
        migrations.RemoveField(
            model_name='resourceinclasstemplate',
            name='time_patterns',
        ),
    ]
