# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0004_auto_20170413_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='rest_time',
        ),
        migrations.RemoveField(
            model_name='scheduledclass',
            name='asked_assistants',
        ),
        migrations.RemoveField(
            model_name='scheduledclass',
            name='asked_for_resources',
        ),
        migrations.RemoveField(
            model_name='scheduledclass',
            name='asked_instructor',
        ),
        migrations.RemoveField(
            model_name='scheduledclass',
            name='asked_students',
        ),
        migrations.RemoveField(
            model_name='scheduledclass',
            name='invoiced_students',
        ),
    ]
