# Generated by Django 2.1.2 on 2018-11-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0006_auto_20170523_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='django_user',
        ),
        migrations.RemoveField(
            model_name='personinclasstemplate',
            name='class_template',
        ),
        migrations.RemoveField(
            model_name='personinclasstemplate',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personinscheduledclass',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personinscheduledclass',
            name='scheduled_class',
        ),
        migrations.RemoveField(
            model_name='resourcecontrol',
            name='person',
        ),
        migrations.RemoveField(
            model_name='resourcecontrol',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resourceinclasstemplate',
            name='class_template',
        ),
        migrations.RemoveField(
            model_name='resourceinclasstemplate',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resourceinscheduledclass',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resourceinscheduledclass',
            name='scheduled_class',
        ),
        migrations.RemoveField(
            model_name='scheduledclass',
            name='class_template',
        ),
        migrations.RemoveField(
            model_name='timepattern',
            name='person',
        ),
        migrations.RemoveField(
            model_name='timepattern',
            name='resource',
        ),
        migrations.DeleteModel(
            name='ClassTemplate',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PersonInClassTemplate',
        ),
        migrations.DeleteModel(
            name='PersonInScheduledClass',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='ResourceControl',
        ),
        migrations.DeleteModel(
            name='ResourceInClassTemplate',
        ),
        migrations.DeleteModel(
            name='ResourceInScheduledClass',
        ),
        migrations.DeleteModel(
            name='ScheduledClass',
        ),
        migrations.DeleteModel(
            name='TimePattern',
        ),
    ]
