# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20170514_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumabletostock',
            name='product_url',
            field=models.URLField(blank=True, help_text='If to be purchased online, specify an URL at the preferred store.', null=True),
        ),
        migrations.AlterField(
            model_name='consumabletostock',
            name='short_desc',
            field=models.CharField(help_text="The item's name or a short description.", max_length=60),
        ),
    ]
