# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20170515_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumabletostock',
            name='min_level_unit',
        ),
        migrations.RemoveField(
            model_name='consumabletostock',
            name='restock_required',
        ),
        migrations.AddField(
            model_name='consumabletostock',
            name='curr_level',
            field=models.IntegerField(default=0, help_text='The current inventory level *in the warehouse* (not displayed for sale) '),
        ),
        migrations.AddField(
            model_name='consumabletostock',
            name='level_unit',
            field=models.CharField(default='?', help_text='The units used for level values', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumabletostock',
            name='min_level',
            field=models.IntegerField(default=0, help_text='Restock when inventory level *in the warehouse* (not displayed for sale) reaches this low level'),
        ),
    ]
