# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 21:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20170606_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the map, e.g. 'Main Floor'", max_length=40)),
                ('url', models.URLField(help_text='The map as a raster or vector image.')),
            ],
        ),
        migrations.CreateModel(
            name='PointOnMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(default='Not yet defined.', help_text='A short description/name for this map point.', max_length=40)),
                ('x', models.FloatField(help_text='X position on map. 0 is left side, 1 is right side.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('y', models.FloatField(help_text='Y position on map. 0 is bottom side, 1 is top side.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('map', models.ForeignKey(help_text='The map on which this location appears.', on_delete=django.db.models.deletion.PROTECT, to='inventory.Map')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='x',
        ),
        migrations.RemoveField(
            model_name='location',
            name='y',
        ),
        migrations.RemoveField(
            model_name='location',
            name='z',
        ),
        migrations.AddField(
            model_name='location',
            name='designated_use',
            field=models.CharField(default='Not yet specified.', help_text="What the space is and isn't supposed to be used for.", max_length=40),
        ),
        migrations.AddField(
            model_name='location',
            name='long_desc',
            field=models.TextField(blank=True, help_text="More info or some keywords like 'glue', 'keyboards', etc.", max_length=1024),
        ),
        migrations.AddField(
            model_name='location',
            name='owning_shop',
            field=models.ForeignKey(blank=True, default=None, help_text='The shop to which this location belongs.', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Shop'),
        ),
        migrations.AddField(
            model_name='location',
            name='volume',
            field=models.FloatField(blank=True, help_text='The realistically useable volume of the location in cubic feet.', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='short_desc',
            field=models.CharField(default='Not yet defined.', help_text='A short description/name for the location.', max_length=40),
        ),
        migrations.AddField(
            model_name='location',
            name='point_on_map',
            field=models.ForeignKey(blank=True, default=None, help_text='A point on a map that helps people find this location.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.PointOnMap'),
        ),
    ]
