# Generated by Django 2.1 on 2018-10-07 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('inventory', '0008_tool_serial_num'), ('inventory', '0009_auto_20181007_1252')]

    dependencies = [
        ('inventory', '0007_auto_20171103_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='serial_num',
            field=models.CharField(blank=True, default='', help_text='Serial# of the tool.', max_length=40),
        ),
        migrations.AlterField(
            model_name='tool',
            name='loan_terms',
            field=models.TextField(blank=True, default='', help_text='If tool is loaned, these are the terms specified by the loaner.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='tool',
            name='loaned_by',
            field=models.ForeignKey(blank=True, default=None, help_text='If tool is loaned, this is the member who loaned it to us.', null=True, on_delete=django.db.models.deletion.PROTECT, to='members.Member'),
        ),
    ]
