# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-03 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bzw_ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblocktype',
            name='is_default',
            field=models.BooleanField(default=False, help_text='This block type should be the default for times not explicitly included in a block.'),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='duration',
            field=models.DurationField(blank=True, help_text='The duration/length of the time block (HH:MM:SS).', null=True),
        ),
    ]
