# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 18:10
from __future__ import unicode_literals

import abutils.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20170831_1521'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='witness',
            field=models.ForeignKey(blank=True, help_text='A director or officer that witnessed the work.', null=True, on_delete=django.db.models.deletion.PROTECT, to='members.Member'),
        ),
        migrations.AddField(
            model_name='work',
            name='work_start_time',
            field=models.TimeField(blank=True, help_text='The time at which work began on the task.', null=True),
        ),
        migrations.AlterField(
            model_name='recurringtasktemplate',
            name='eligible_claimants',
            field=models.ManyToManyField(blank=True, help_text='Anybody chosen is eligible to claim the task.<br/>', related_name='claimable_recurringtasktemplate', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='recurringtasktemplate',
            name='eligible_tags',
            field=models.ManyToManyField(blank=True, help_text='Anybody that has one of the chosen tags is eligible to claim the task.<br/>', related_name='claimable_recurringtasktemplate', to='members.Tag'),
        ),
        migrations.AlterField(
            model_name='recurringtasktemplate',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The member that asked for this task to be created or has taken responsibility for its content.<br/>This is almost certainly not the person who will claim the task and do the work.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_recurringtasktemplate', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='recurringtasktemplate',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='If required, a member who will review the work once its completed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewable_recurringtasktemplate', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='recurringtasktemplate',
            name='work_duration',
            field=models.DurationField(blank=True, help_text='Used with work_start_time to specify the time span over which work must occur. <br/>If work_start_time is blank then this should also be blank.', null=True, validators=[abutils.validators.positive_duration]),
        ),
        migrations.AlterField(
            model_name='task',
            name='eligible_claimants',
            field=models.ManyToManyField(blank=True, help_text='Anybody chosen is eligible to claim the task.<br/>', related_name='claimable_task', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='task',
            name='eligible_tags',
            field=models.ManyToManyField(blank=True, help_text='Anybody that has one of the chosen tags is eligible to claim the task.<br/>', related_name='claimable_task', to='members.Tag'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The member that asked for this task to be created or has taken responsibility for its content.<br/>This is almost certainly not the person who will claim the task and do the work.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_task', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='If required, a member who will review the work once its completed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewable_task', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='task',
            name='work_duration',
            field=models.DurationField(blank=True, help_text='Used with work_start_time to specify the time span over which work must occur. <br/>If work_start_time is blank then this should also be blank.', null=True, validators=[abutils.validators.positive_duration]),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_date',
            field=models.DateField(help_text='The date on which the work was started.'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_duration',
            field=models.DurationField(blank=True, help_text='Time spent working the task. If blank, work is in progress.', null=True),
        ),
    ]
