# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-11 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180306_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAccountEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(help_text='Explanation of this change.', max_length=80)),
                ('when', models.DateTimeField(default=django.utils.timezone.now, help_text='Date/time of the change.')),
                ('expires', models.DateTimeField(blank=True, default=None, help_text='For credits, the OPTIONAL date on which it expires.', null=True)),
                ('change', models.DecimalField(decimal_places=2, help_text='The amount added (positive) or deleted (negative).', max_digits=4)),
                ('worker', models.ForeignKey(help_text='The worker whose balance is changing.', on_delete=django.db.models.deletion.CASCADE, to='tasks.Worker')),
            ],
            options={
                'ordering': ['when'],
            },
        ),
    ]
