# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-11 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20180311_1252'),
        ('tasks', '0004_timeaccountentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeaccountentry',
            options={'ordering': ['when'], 'verbose_name_plural': 'time account entries'},
        ),
        migrations.AddField(
            model_name='timeaccountentry',
            name='play',
            field=models.ForeignKey(blank=True, help_text='For debits, a link to the associated membership, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Membership'),
        ),
        migrations.AddField(
            model_name='timeaccountentry',
            name='work',
            field=models.ForeignKey(blank=True, help_text='For credits, a link to the associated work entry, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Work'),
        ),
        migrations.AlterField(
            model_name='timeaccountentry',
            name='change',
            field=models.DecimalField(decimal_places=2, help_text='The amount (in hours) added (positive) or deleted (negative).', max_digits=4),
        ),
    ]
