# Generated by Django 2.0.3 on 2018-04-05 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20180311_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeaccountentry',
            name='expiration',
            field=models.ForeignKey(blank=True, default=None, help_text='For credits, the corresponding entry that expires the unused portion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit', to='tasks.TimeAccountEntry'),
        ),
        migrations.AddField(
            model_name='timeaccountentry',
            name='type',
            field=models.CharField(choices=[('DEP', 'Deposit'), ('WTH', 'Withdrawal'), ('EXP', 'Expiration'), ('ADJ', 'Adjustment')], default='XXX', help_text='The priority of the task, compared to other tasks.', max_length=3),
            preserve_default=False,
        ),
    ]
