# Generated by Django 2.0.3 on 2018-05-19 19:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_auto_20180422_1221'),
        ('tasks', '0008_auto_20180519_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAccountEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEP', 'Deposit'), ('WTH', 'Withdrawal'), ('EXP', 'Expiration'), ('ADJ', 'Adjustment')], help_text='The priority of the task, compared to other tasks.', max_length=3)),
                ('explanation', models.CharField(help_text='Explanation of this change.', max_length=80)),
                ('when', models.DateTimeField(default=django.utils.timezone.now, help_text='Date/time of the change.')),
                ('expires', models.DateTimeField(blank=True, default=None, help_text='For credits, the OPTIONAL date on which it expires.', null=True)),
                ('change', models.DecimalField(decimal_places=2, help_text='The amount (in hours) added (positive) or deleted (negative).', max_digits=4)),
                ('expiration', models.ForeignKey(blank=True, default=None, help_text='For credits, the corresponding entry that expires the unused portion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit', to='tasks.TimeAccountEntry')),
                ('mship', models.ForeignKey(blank=True, help_text='For debits, a link to the associated membership, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Membership')),
                ('play', models.ForeignKey(blank=True, help_text='For debits, a link to the associated play, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Play')),
                ('work', models.ForeignKey(blank=True, help_text='For credits, a link to the associated work, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Work')),
                ('worker', models.ForeignKey(help_text='The worker whose balance is changing.', on_delete=django.db.models.deletion.CASCADE, to='tasks.Worker')),
            ],
            options={
                'verbose_name_plural': 'time account entries',
                'ordering': ['when'],
            },
        ),
    ]
