# Generated by Django 2.0.3 on 2018-05-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_timeaccountentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ['play_date'], 'verbose_name_plural': 'Play'},
        ),
    ]
