# Generated by Django 2.0.3 on 2018-05-21 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_auto_20180422_1221'),
        ('tasks', '0010_auto_20180521_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateEligibleClaimant2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1ST', 'Default Claimant'), ('2ND', 'Eligible, 2nd String'), ('3RD', 'Eligible, 3rd String')], help_text='The type of this relationship.', max_length=3)),
                ('should_nag', models.BooleanField(default=False, help_text='If true, member will be encouraged to work instances of the template.')),
                ('member', models.ForeignKey(help_text='The member in this relation.', on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.RemoveField(
            model_name='templateeligibleclaimants2',
            name='member',
        ),
        migrations.RemoveField(
            model_name='templateeligibleclaimants2',
            name='template',
        ),
        migrations.AlterField(
            model_name='eligibleclaimant2',
            name='type',
            field=models.CharField(choices=[('1ST', 'Default Claimant'), ('2ND', 'Eligible, 2nd String'), ('3RD', 'Eligible, 3rd String'), ('DEC', 'Will Not Claim')], help_text='The type of this relationship.', max_length=3),
        ),
        migrations.AlterField(
            model_name='recurringtasktemplate',
            name='eligible_claimants_2',
            field=models.ManyToManyField(blank=True, help_text='Anybody chosen is eligible to claim the task.<br/>', related_name='claimable2_recurringtasktemplate', through='tasks.TemplateEligibleClaimant2', to='members.Member'),
        ),
        migrations.DeleteModel(
            name='TemplateEligibleClaimants2',
        ),
        migrations.AddField(
            model_name='templateeligibleclaimant2',
            name='template',
            field=models.ForeignKey(help_text='The task in this relation.', on_delete=django.db.models.deletion.CASCADE, to='tasks.RecurringTaskTemplate'),
        ),
    ]
