# Generated by Django 2.0.3 on 2018-05-23 06:44

from django.db import migrations, models


sql = """
insert into tasks_eligibleclaimant2 (type, should_nag, member_id, task_id)
select '2ND' as type, true as should_nag, member_id, task_id
from tasks_task_eligible_claimants;

insert into tasks_templateeligibleclaimant2 (type, should_nag, member_id, template_id)
select '2ND' as type, true as should_nag, member_id, recurringtasktemplate_id
from tasks_recurringtasktemplate_eligible_claimants;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20180521_1324'),
    ]

    operations = [

        migrations.RunSQL(sql),

        migrations.RemoveField(
            model_name='recurringtasktemplate',
            name='eligible_claimants',
        ),
        migrations.RemoveField(
            model_name='task',
            name='eligible_claimants',
        ),
        migrations.AlterField(
            model_name='eligibleclaimant2',
            name='type',
            field=models.CharField(choices=[('1ST', 'Default Claimant'), ('2ND', 'Eligible, 2nd String'), ('3RD', 'Eligible, 3rd String'), ('DEC', 'Will Not Claim'), ('EXP', 'Did Not Respond')], help_text='The type of this relationship.', max_length=3),
        ),
    ]
