# Generated by Django 2.0.3 on 2018-06-23 02:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_class_class_x_person_classpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classpayment',
            name='class_x_person',
        ),
        migrations.AddField(
            model_name='class_x_person',
            name='payment',
            field=models.OneToOneField(blank=True, help_text='The associated payment, if any exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.ClassPayment'),
        ),
        migrations.AlterField(
            model_name='class_x_person',
            name='status_updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The date/time on which the current status was last updated.', null=True),
        ),
    ]
