# Generated by Django 2.0.3 on 2018-06-23 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_auto_20180422_1221'),
        ('tasks', '0014_auto_20180622_1907'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class_x_person',
            unique_together={('the_class', 'the_person')},
        ),
        migrations.AlterUniqueTogether(
            name='classpayment',
            unique_together={('the_class', 'the_person')},
        ),
    ]
