# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-04 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0041_auto_20160912_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='recurring_task_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='tasks.RecurringTaskTemplate'),
        ),
        migrations.AlterField(
            model_name='unavailabledates',
            name='who',
            field=models.ForeignKey(blank=True, help_text='The worker who will be unavailable.', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Worker'),
        ),
    ]
