# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-04 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0042_auto_20161204_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='missed_date_action',
        ),
    ]
