# Generated by Django 2.0.3 on 2018-07-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0002_playlogentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlogentry',
            options={'verbose_name': 'Play Log Entry', 'verbose_name_plural': 'Play Log Entries'},
        ),
        migrations.AlterField(
            model_name='playlogentry',
            name='track_type',
            field=models.IntegerField(choices=[(0, 'Music'), (1, 'Jingle'), (2, 'Sweeper'), (3, 'Voiceover'), (4, 'Commercial'), (5, 'Internet Stream'), (6, 'Other'), (7, 'Variable Duration File'), (8, 'Request'), (9, 'News'), (10, 'Playlist Event'), (11, 'File By Date'), (12, 'Newest From Folder')], help_text='The type of the item in the Radio DJ database.'),
        ),
    ]
