# Generated by Django 2.0.3 on 2018-07-04 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0003_auto_20180702_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnAirPersonalitySocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.URLField(help_text="URL for the personality's social media account.")),
                ('personality', models.ForeignKey(help_text='The on air personality associated with this social media account.', on_delete=django.db.models.deletion.CASCADE, to='kmkr.OnAirPersonality')),
            ],
            options={
                'verbose_name': "On Air Personality's Social Media",
                'verbose_name_plural': "On Air Personality's Social Media",
            },
        ),
        migrations.RemoveField(
            model_name='underwritingspots',
            name='title',
        ),
        migrations.AddField(
            model_name='underwritingspots',
            name='track_id',
            field=models.IntegerField(blank=True, help_text='The ID of the associated track on Radio DJ.', null=True),
        ),
    ]
