# Generated by Django 2.0.3 on 2018-07-07 21:09

from django.db import migrations, models
import django.db.models.deletion
from kmkr.models import PlayLogEntry, Track


def forward_func(apps, schema_editor):
    for aired in PlayLogEntry.objects.all():
        track, _ = Track.objects.get_or_create(
            radiodj_id=aired.radiodj_id,
            defaults={
                "duration": aired.duration,
                "title": aired.title,
                "artist": aired.artist,
                "radiodj_id": aired.radiodj_id,
                "track_type": aired.track_type,
            }
        )
        aired.track = track
        aired.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0004_auto_20180704_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(help_text='The expected duration of the item.')),
                ('title', models.CharField(help_text='The title of the item.', max_length=128)),
                ('artist', models.CharField(help_text='The artist/dj/etc featured in this item.', max_length=128)),
                ('radiodj_id', models.IntegerField(help_text='The track ID of the item in the Radio DJ database.')),
                ('track_type', models.IntegerField(choices=[(0, 'Music'), (1, 'Jingle'), (2, 'Sweeper'), (3, 'Voiceover'), (4, 'Commercial'), (5, 'Internet Stream'), (6, 'Other'), (7, 'Variable Duration File'), (8, 'Request'), (9, 'News'), (10, 'Playlist Event'), (11, 'File By Date'), (12, 'Newest From Folder')], help_text='The type of the item in the Radio DJ database.')),
            ],
        ),
        migrations.RenameField(
            model_name='playlogentry',
            old_name='track_id',
            new_name='radiodj_id',
        ),
        migrations.AlterField(
            model_name='playlogentry',
            name='artist',
            field=models.CharField(blank=True, help_text='The artist/dj/etc featured in this item.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='playlogentry',
            name='duration',
            field=models.DurationField(blank=True, help_text='The expected duration of the item.', null=True),
        ),
        migrations.AlterField(
            model_name='playlogentry',
            name='title',
            field=models.CharField(blank=True, help_text='The title of the item.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='playlogentry',
            name='track_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Music'), (1, 'Jingle'), (2, 'Sweeper'), (3, 'Voiceover'), (4, 'Commercial'), (5, 'Internet Stream'), (6, 'Other'), (7, 'Variable Duration File'), (8, 'Request'), (9, 'News'), (10, 'Playlist Event'), (11, 'File By Date'), (12, 'Newest From Folder')], help_text='The type of the item in the Radio DJ database.', null=True),
        ),
        migrations.AddField(
            model_name='playlogentry',
            name='track',
            field=models.ForeignKey(blank=True, default=None, help_text='The track that was aired.', null=True, on_delete=django.db.models.deletion.PROTECT, to='kmkr.Track'),
        ),

        #migrations.RunPython(forward_func)
    ]
