# Generated by Django 2.0.3 on 2018-07-08 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0006_auto_20180707_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlogentry',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='playlogentry',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='playlogentry',
            name='radiodj_id',
        ),
        migrations.RemoveField(
            model_name='playlogentry',
            name='title',
        ),
        migrations.RemoveField(
            model_name='playlogentry',
            name='track_type',
        ),
        migrations.AlterField(
            model_name='playlogentry',
            name='track',
            field=models.ForeignKey(default=-99, help_text='The track which was aired.', on_delete=django.db.models.deletion.PROTECT, to='kmkr.Track'),
            preserve_default=False,
        ),
    ]
