# Generated by Django 2.0.3 on 2018-07-08 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_auto_20180422_1221'),
        ('kmkr', '0007_auto_20180707_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(2, 'Two thumbs up'), (1, 'One thumb up'), (0, 'Neutral'), (-1, 'One thumb down'), (-2, 'Two thumbs down')], help_text='The rating')),
                ('what', models.ForeignKey(help_text='What was rated.', on_delete=django.db.models.deletion.CASCADE, to='kmkr.PlayLogEntry')),
                ('who', models.ForeignKey(help_text='Person who rated.', on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('what', 'who')},
        ),
    ]
