# Generated by Django 2.0.3 on 2018-07-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0009_auto_20180708_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='fridays',
        ),
        migrations.RemoveField(
            model_name='show',
            name='minute_duration',
        ),
        migrations.RemoveField(
            model_name='show',
            name='mondays',
        ),
        migrations.RemoveField(
            model_name='show',
            name='saturdays',
        ),
        migrations.RemoveField(
            model_name='show',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='show',
            name='sundays',
        ),
        migrations.RemoveField(
            model_name='show',
            name='thursdays',
        ),
        migrations.RemoveField(
            model_name='show',
            name='tuesdays',
        ),
        migrations.RemoveField(
            model_name='show',
            name='wednesdays',
        ),
    ]
