# Generated by Django 2.0.3 on 2018-07-15 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0011_auto_20180710_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlogentry',
            name='show',
            field=models.ForeignKey(blank=True, help_text='The associated show, if track was played as part of a show.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kmkr.Show'),
        ),
        migrations.AddField(
            model_name='playlogentry',
            name='show_date',
            field=models.DateField(blank=True, help_text='If show is specified, this is the date on which the show aired.', null=True),
        ),
        migrations.AlterField(
            model_name='playlogentry',
            name='start',
            field=models.DateTimeField(blank=True, help_text='The exact datetime (within a few seconds) that play began.', null=True),
        ),
        migrations.AlterField(
            model_name='playlogentry',
            name='track',
            field=models.ForeignKey(help_text='The track which was played.', on_delete=django.db.models.deletion.PROTECT, to='kmkr.Track'),
        ),
    ]
