# Generated by Django 2.0.3 on 2018-07-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0014_auto_20180730_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualplaylistentry',
            options={'verbose_name': 'Manual Playlist Entry', 'verbose_name_plural': 'Manual Playlist Entries'},
        ),
    ]
