# Generated by Django 2.0.3 on 2018-07-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0015_auto_20180730_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlogentry',
            name='show',
        ),
        migrations.RemoveField(
            model_name='playlogentry',
            name='show_date',
        ),
        migrations.AlterField(
            model_name='playlogentry',
            name='start',
            field=models.DateTimeField(help_text='The exact datetime (within a few seconds) that play began.'),
        ),
    ]
