# Generated by Django 2.0.3 on 2018-08-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0016_auto_20180730_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualplaylistentry',
            name='artist',
            field=models.CharField(blank=True, default='', help_text='The artist who performed the track.', max_length=128),
        ),
        migrations.AlterField(
            model_name='manualplaylistentry',
            name='duration',
            field=models.CharField(blank=True, default='', help_text='The duration of the track as MM:SS.', max_length=5),
        ),
        migrations.AlterField(
            model_name='manualplaylistentry',
            name='title',
            field=models.CharField(blank=True, default='', help_text='The title of the track.', max_length=128),
        ),
    ]
