# Generated by Django 2.0.3 on 2018-08-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0017_auto_20180804_2111'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='manualplaylistentry',
            unique_together={('live_show_instance', 'sequence')},
        ),
    ]
