# Generated by Django 2.0.3 on 2018-08-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0018_auto_20180808_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='showinstance',
            name='production_method',
            field=models.CharField(choices=[('LIV', 'Live'), ('PRE', 'Prerecorded'), ('RPT', 'Repeat')], default='LIV', help_text='For this particular ShowInstance. Might differ from default in ShowTime.', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showtime',
            name='production_method',
            field=models.CharField(choices=[('LIV', 'Live'), ('PRE', 'Prerecorded'), ('RPT', 'Repeat')], help_text='Default production method for this show time.', max_length=3),
        ),
    ]
