# Generated by Django 2.0.3 on 2018-08-10 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0019_auto_20180810_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='The date of the broadcast.', null=True)),
                ('host_checked_in', models.TimeField(blank=True, help_text='Specify for original live broadcast, but not for repeat broadcasts.', null=True)),
                ('production_method', models.CharField(choices=[('LIV', 'Live'), ('PRE', 'Prerecorded'), ('RPT', 'Repeat')], help_text='For this particular broadcast. Might differ from default in ShowTime.', max_length=3)),
                ('episode', models.ForeignKey(blank=True, help_text='The episode that will be broadcast.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kmkr.Show')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_broadcast', models.DateField(blank=True, help_text='The date of the first broadcast of this episode.', null=True)),
                ('title', models.CharField(blank=True, default='', help_text='The (optional) title of this episode.', max_length=128)),
                ('show', models.ForeignKey(blank=True, help_text='Specify the show of which this is an episode.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kmkr.Show')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(help_text='The position of the track in the playlist.')),
                ('artist', models.CharField(blank=True, default='', help_text='The artist who performed the track.', max_length=128)),
                ('title', models.CharField(blank=True, default='', help_text='The title of the track.', max_length=128)),
                ('duration', models.CharField(blank=True, default='', help_text='The duration of the track as MM:SS.', max_length=5)),
                ('episode', models.ForeignKey(help_text='The associated episode.', on_delete=django.db.models.deletion.CASCADE, to='kmkr.Episode')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='manualplaylistentry',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='manualplaylistentry',
            name='live_show_instance',
        ),
        migrations.RemoveField(
            model_name='showinstance',
            name='repeat_of',
        ),
        migrations.RemoveField(
            model_name='showinstance',
            name='show',
        ),
        migrations.DeleteModel(
            name='ManualPlayListEntry',
        ),
        migrations.DeleteModel(
            name='ShowInstance',
        ),
        migrations.AlterUniqueTogether(
            name='episodetrack',
            unique_together={('episode', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('show', 'first_broadcast')},
        ),
    ]
