# Generated by Django 2.0.3 on 2018-08-11 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0020_auto_20180810_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcast',
            name='production_method',
        ),
        migrations.AddField(
            model_name='broadcast',
            name='type',
            field=models.CharField(choices=[('1ST', 'First Broadcast'), ('RPT', 'Repeat Broadcast')], default='1ST', help_text='Is this an original or repeat broadcast?', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='date',
            field=models.DateField(help_text='The date of the broadcast.'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='episode',
            field=models.ForeignKey(help_text='The episode that will be broadcast.', on_delete=django.db.models.deletion.PROTECT, to='kmkr.Episode'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='production_method',
            field=models.CharField(choices=[('LIV', 'Live'), ('PRE', 'Prerecorded')], help_text='Default production method for this show time.', max_length=3),
        ),
    ]
