# Generated by Django 2.0.3 on 2018-08-14 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0021_auto_20180811_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='underwritingspots',
            name='holds_donation',
        ),
    ]
