# Generated by Django 2.0.3 on 2018-08-18 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0024_auto_20180817_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodetrack',
            name='trackBroadcast',
            field=models.ForeignKey(blank=True, help_text="The record of this track's broadcast, if it was broadcast.", null=True, on_delete=django.db.models.deletion.PROTECT, to='kmkr.PlayLogEntry'),
        ),
    ]
