# Generated by Django 2.0.3 on 2018-08-18 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0025_episodetrack_trackbroadcast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodetrack',
            old_name='trackBroadcast',
            new_name='track_broadcast',
        ),
    ]
