# Generated by Django 2.1 on 2018-08-26 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_auto_20180611_1321'),
        ('kmkr', '0026_auto_20180817_2122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnderwritingSpots',
            new_name='UnderwritingAgreement',
        ),
        migrations.RenameModel(
            old_name='UnderwritingLogEntry',
            new_name='UnderwritingBroadcast',
        ),
    ]
