# Generated by Django 2.1 on 2018-08-26 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0027_auto_20180825_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='underwritingagreement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='underwritingbroadcast',
            options={},
        ),
        migrations.AddField(
            model_name='underwritingagreement',
            name='spots_included',
            field=models.IntegerField(default=0, help_text='The number of spots included in this agreement.', validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
