# Generated by Django 2.1 on 2018-08-26 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0029_auto_20180825_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderwritingSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(help_text="The time to broadcast the underwriter's spot.")),
                ('sundays', models.BooleanField(default=False, verbose_name='Sun')),
                ('mondays', models.BooleanField(default=False, verbose_name='Mon')),
                ('tuesdays', models.BooleanField(default=False, verbose_name='Tue')),
                ('wednesdays', models.BooleanField(default=False, verbose_name='Wed')),
                ('thursdays', models.BooleanField(default=False, verbose_name='Thu')),
                ('fridays', models.BooleanField(default=False, verbose_name='Fri')),
                ('saturdays', models.BooleanField(default=False, verbose_name='Sat')),
            ],
        ),
        migrations.RemoveField(
            model_name='underwritingagreement',
            name='specific_shows',
        ),
        migrations.AlterField(
            model_name='underwritingagreement',
            name='qty_sold',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='underwritingschedule',
            name='agreement',
            field=models.ForeignKey(help_text='The associated agreement.', on_delete=django.db.models.deletion.CASCADE, to='kmkr.UnderwritingAgreement'),
        ),
    ]
