# Generated by Django 2.1 on 2018-08-26 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0030_auto_20180825_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='underwritingagreement',
            name='custom_details',
        ),
        migrations.RemoveField(
            model_name='underwritingagreement',
            name='slot',
        ),
    ]
