# Generated by Django 2.1 on 2018-08-28 18:50

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_auto_20180611_1321'),
        ('kmkr', '0032_auto_20180825_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderwritingBroadcastLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_read', models.DateTimeField(help_text='The date & time the spot was read on-air.')),
            ],
        ),
        migrations.CreateModel(
            name='UnderwritingBroadcastSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_spots', models.IntegerField(help_text='The number of spots to broadcast in this time slot.', validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.TimeField(help_text="The time to broadcast the underwriter's spot.")),
                ('weekdays', models.BooleanField(default=False)),
                ('weekend', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UnderwritingDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='The UNIT price at which this/these item(s) sold.', max_digits=6)),
                ('qty_sold', models.IntegerField(blank=True, default=None, help_text='The quantity of the item sold. Leave blank if quantity is not known.', null=True)),
                ('start_date', models.DateField(default=datetime.date.today, help_text="Underwriter's preference for first day on which a spot will run.")),
                ('end_date', models.DateField(default=datetime.date.today, help_text="Underwriter's preference for last day on which a spot will run.")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnderwritingQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_price', models.DecimalField(decimal_places=2, help_text='The price to purchase an instance this agreement.', max_digits=6)),
                ('spot_seconds', models.IntegerField(help_text='The length of each spot in seconds.', validators=[django.core.validators.MinValueValidator(0)])),
                ('track_id', models.IntegerField(blank=True, help_text='The ID of the associated track on Radio DJ.', null=True)),
                ('script', models.TextField(help_text='The text to read on-air.', max_length=2048)),
                ('prepared_for', models.ForeignKey(help_text='The business/organization for whom this quote was prepared.', on_delete=django.db.models.deletion.CASCADE, to='books.Entity')),
            ],
        ),
        migrations.RemoveField(
            model_name='underwritingagreement',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='underwritingbroadcast',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='underwritingschedule',
            name='agreement',
        ),
        migrations.DeleteModel(
            name='UnderwritingAgreement',
        ),
        migrations.DeleteModel(
            name='UnderwritingBroadcast',
        ),
        migrations.DeleteModel(
            name='UnderwritingSchedule',
        ),
        migrations.AddField(
            model_name='underwritingdeal',
            name='quote',
            field=models.ForeignKey(help_text='The associated quote, which contains the terms of this dea.', on_delete=django.db.models.deletion.PROTECT, to='kmkr.UnderwritingQuote'),
        ),
        migrations.AddField(
            model_name='underwritingdeal',
            name='sale',
            field=models.ForeignKey(help_text='The sale for which this is a line item.', on_delete=django.db.models.deletion.CASCADE, to='books.Sale'),
        ),
        migrations.AddField(
            model_name='underwritingbroadcastschedule',
            name='agreement',
            field=models.ForeignKey(help_text='The associated agreement.', on_delete=django.db.models.deletion.CASCADE, to='kmkr.UnderwritingQuote'),
        ),
        migrations.AddField(
            model_name='underwritingbroadcastlog',
            name='deal',
            field=models.ForeignKey(help_text='The associated sale line item.', on_delete=django.db.models.deletion.PROTECT, to='kmkr.UnderwritingDeal'),
        ),
        migrations.AddField(
            model_name='underwritingbroadcastlog',
            name='schedule',
            field=models.ForeignKey(help_text='The associated schedule line item in the sale.', on_delete=django.db.models.deletion.PROTECT, to='kmkr.UnderwritingBroadcastSchedule'),
        ),
    ]
