# Generated by Django 2.1 on 2018-08-28 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0033_auto_20180828_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='underwritingquote',
            name='active',
            field=models.BooleanField(default=True, help_text='Checked if this quote is still being offered to the underwriter.'),
        ),
        migrations.AddField(
            model_name='underwritingquote',
            name='date_prepared',
            field=models.DateField(default=datetime.date.today, help_text='The date on which this quote was prepared.'),
        ),
    ]
