# Generated by Django 2.1 on 2018-08-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0034_auto_20180828_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='underwritingbroadcastschedule',
            name='weekdays',
        ),
        migrations.RemoveField(
            model_name='underwritingbroadcastschedule',
            name='weekend',
        ),
        migrations.AddField(
            model_name='underwritingbroadcastschedule',
            name='fridays',
            field=models.BooleanField(default=False, verbose_name='Fri'),
        ),
        migrations.AddField(
            model_name='underwritingbroadcastschedule',
            name='mondays',
            field=models.BooleanField(default=False, verbose_name='Mon'),
        ),
        migrations.AddField(
            model_name='underwritingbroadcastschedule',
            name='saturdays',
            field=models.BooleanField(default=False, verbose_name='Sat'),
        ),
        migrations.AddField(
            model_name='underwritingbroadcastschedule',
            name='sundays',
            field=models.BooleanField(default=False, verbose_name='Sun'),
        ),
        migrations.AddField(
            model_name='underwritingbroadcastschedule',
            name='thursdays',
            field=models.BooleanField(default=False, verbose_name='Thu'),
        ),
        migrations.AddField(
            model_name='underwritingbroadcastschedule',
            name='tuesdays',
            field=models.BooleanField(default=False, verbose_name='Tue'),
        ),
        migrations.AddField(
            model_name='underwritingbroadcastschedule',
            name='wednesdays',
            field=models.BooleanField(default=False, verbose_name='Wed'),
        ),
    ]
