# Generated by Django 2.1 on 2018-08-30 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kmkr', '0035_auto_20180829_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='underwritingbroadcastlog',
            name='schedule',
            field=models.ForeignKey(help_text='The associated schedule the quote.', on_delete=django.db.models.deletion.PROTECT, to='kmkr.UnderwritingBroadcastSchedule'),
        ),
        migrations.AlterField(
            model_name='underwritingbroadcastschedule',
            name='agreement',
            field=models.ForeignKey(help_text='The associated quote.', on_delete=django.db.models.deletion.CASCADE, to='kmkr.UnderwritingQuote'),
        ),
        migrations.AlterField(
            model_name='underwritingquote',
            name='quoted_price',
            field=models.DecimalField(decimal_places=2, help_text='The quoted price.', max_digits=6),
        ),
        migrations.AlterUniqueTogether(
            name='underwritingbroadcastlog',
            unique_together={('deal', 'when_read')},
        ),
    ]
