# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushover',
            options={'verbose_name': 'Notification Mechanism'},
        ),
        migrations.AddField(
            model_name='pushover',
            name='mechanism',
            field=models.CharField(choices=[('PSH', 'Pushover'), ('EML', 'Email-to-SMS Gateway')], default='PSH', max_length=3),
        ),
        migrations.AlterField(
            model_name='pushover',
            name='key',
            field=models.CharField(help_text='User Key for Pushover, phone number for Text.', max_length=30),
        ),
    ]
