# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20170405_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the campaign.', max_length=20, unique=True)),
                ('description', models.TextField(help_text='Some information about the campaign.', max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='membershipgiftcard',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='The membership campaign that this card/code belongs to, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, to='members.MembershipCampaign'),
        ),
    ]
