# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20170607_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='key_allowed',
            field=models.BooleanField(default=False, help_text='True if the membership allows use of a previously granted key, if any.'),
        ),
    ]
