# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 21:07
from __future__ import unicode_literals

import books.models
import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20170624_1354'),
        ('members', '0004_membership_key_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, help_text='The first day on which the membership is valid.')),
                ('end_date', models.DateField(default=datetime.date.today, help_text='The last day on which the membership is valid.')),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The price at which this item sold.', max_digits=6)),
                ('ctrlid', models.CharField(default=members.models.next_keyfee_ctrlid, help_text="Payment processor's id for this line item if it was part of an online purchase.", max_length=40, unique=True)),
                ('protected', models.BooleanField(default=False, help_text='Protect against further auto processing by ETL, etc. Prevents overwrites of manually entered data.')),
            ],
            options={
                'abstract': False,
            },
            bases=(books.models.JournalLiner, models.Model),
        ),
        migrations.RemoveField(
            model_name='membership',
            name='key_allowed',
        ),
        migrations.AddField(
            model_name='keyfee',
            name='membership',
            field=models.OneToOneField(blank=True, default=None, help_text='The associated membership. MUST be specified, eventually!', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Membership'),
        ),
        migrations.AddField(
            model_name='keyfee',
            name='sale',
            field=models.ForeignKey(blank=True, default=None, help_text='The sale that includes this line item.', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Sale'),
        ),
    ]
