# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 23:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20170807_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyfee',
            name='end_date',
            field=models.DateField(default=datetime.date.today, help_text='End date of portion of membership covered by this fee.'),
        ),
        migrations.AlterField(
            model_name='keyfee',
            name='start_date',
            field=models.DateField(default=datetime.date.today, help_text='Start date of portion of membership covered by this fee.'),
        ),
    ]
