# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20171206_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyMembershipEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(help_text='Explanation of this change.', max_length=80)),
                ('when', models.DateTimeField(default=django.utils.timezone.now, help_text='Date/time of the change.')),
                ('change', models.DecimalField(decimal_places=2, help_text='The amount added (positive) or deleted (negative).', max_digits=4)),
                ('member', models.ForeignKey(help_text='The member whose balance is changing.', on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
            options={
                'ordering': ['when'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='hourlymembershipentry',
            unique_together=set([('member', 'when')]),
        ),
    ]
