# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20171216_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlymembershipentry',
            name='expires',
            field=models.DateTimeField(blank=True, default=None, help_text='For credits, the OPTIONAL date on which it expires.', null=True),
        ),
        migrations.AlterField(
            model_name='membershipgiftcard',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='The membership campaign that this card/code belongs to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.MembershipCampaign'),
        ),
        migrations.AlterUniqueTogether(
            name='hourlymembershipentry',
            unique_together=set([]),
        ),
    ]
