# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20180205_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitevent',
            name='sync1',
        ),
    ]
