# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-11 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20180215_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlymembershipentry',
            name='member',
        ),
        migrations.DeleteModel(
            name='HourlyMembershipEntry',
        ),
    ]
