# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 20:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0015_auto_20180311_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('uid', models.CharField(max_length=255)),
                ('extra_data', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='externalid',
            unique_together=set([('provider', 'uid')]),
        ),
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS social_auth_usersocialauth AS SELECT * FROM members_externalid"
        ),
        migrations.RunSQL(
            "INSERT INTO members_externalid SELECT * FROM social_auth_usersocialauth"
        )
    ]
