# Generated by Django 2.0.3 on 2018-04-01 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_auto_20180318_2007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WifiMacDetected',
        ),
    ]
