# Generated by Django 2.0.3 on 2018-04-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_delete_wifimacdetected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitevent',
            name='reason',
            field=models.CharField(blank=True, choices=[('PUB', 'Free public access'), ('CUR', 'Checking out Xerocraft'), ('CLS', 'Attending a class'), ('MEM', 'Membership privileges'), ('CLB', 'Club privileges'), ('GST', 'Guest of a member'), ('VOL', 'Volunteering'), ('OTH', 'Other')], default=None, help_text='The reason for a visit. Not used on Departures.', max_length=3, null=True),
        ),
    ]
