# Generated by Django 2.0.3 on 2018-07-22 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20180722_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagging',
            name='tag',
            field=models.ForeignKey(help_text='The tag assigned to the member.', limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='members.Tag'),
        ),
    ]
