# Generated by Django 2.0.3 on 2018-07-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20180722_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalid',
            name='extra_data',
            field=models.TextField(blank=True),
        ),
    ]
