# Generated by Django 2.1 on 2018-08-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_auto_20180723_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagging',
            old_name='tagged_member',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='member',
            name='tags',
        ),
        migrations.AddField(
            model_name='tagging',
            name='is_tagged',
            field=models.BooleanField(default=True, help_text='If True, the member has this tag.'),
        ),
        migrations.AlterField(
            model_name='tagging',
            name='can_tag',
            field=models.BooleanField(default=False, help_text='If True, the member can tag other members with this tag.'),
        ),
        migrations.AlterUniqueTogether(
            name='tagging',
            unique_together={('member', 'tag')},
        ),
    ]
