# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-26 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0052_auto_20160812_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidmembershipnudge',
            name='member',
        ),
        migrations.AddField(
            model_name='membership',
            name='nudge_count',
            field=models.IntegerField(default=0, help_text='The number of times a renewal reminder was sent.'),
        ),
        migrations.AddField(
            model_name='membership',
            name='when_nudged',
            field=models.DateField(blank=True, default=None, help_text='Most recent date on which a renewal reminder was sent.', null=True),
        ),
        migrations.DeleteModel(
            name='PaidMembershipNudge',
        ),
    ]
