# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-01 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0053_auto_20161026_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='membershipgiftcard',
            name='day_duration',
            field=models.IntegerField(blank=True, default=None, help_text='The number of days of membership this gift card grants when redeemed.', null=True, verbose_name='Days'),
        ),
        migrations.AlterField(
            model_name='membershipgiftcard',
            name='month_duration',
            field=models.IntegerField(blank=True, default=None, help_text='The number of months of membership this gift card grants when redeemed.', null=True, verbose_name='Months'),
        ),
    ]
