# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-17 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0054_auto_20161101_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nag_re_membership',
            field=models.BooleanField(default=False, help_text='If true, person will be nudged (via email) to renew membership.'),
        ),
    ]
