# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0058_receivableinvoice_send_invoice'),
        ('members', '0056_auto_20170124_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='invoice',
            field=models.ForeignKey(blank=True, default=None, help_text='The receivable invoice that includes this line item, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.ReceivableInvoice'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='sale',
            field=models.ForeignKey(blank=True, default=None, help_text='The sale on which this group membership appears as a line item, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Sale'),
        ),
    ]
