# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0057_auto_20170322_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='members_covered',
            field=models.ManyToManyField(through='members.Membership', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='group_tag',
            field=models.ForeignKey(help_text='Group membership is initially populated with the set of people having this tag.', on_delete=django.db.models.deletion.PROTECT, to='members.Tag'),
        ),
    ]
