# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 18:10
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0058_auto_20170324_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='end_date',
            field=models.DateField(default=datetime.date.today, help_text='The last day on which the membership is valid.'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The price at which this item sold.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='start_date',
            field=models.DateField(default=datetime.date.today, help_text='The first day on which the membership is valid.'),
        ),
    ]
