#!/usr/bin/env bash
# transpile.sh executes with working directory $ProjectFileDir$

set -x

cd members/elm-clients/

ELM=ReceptionKiosk.elm
JS=../static/members/ReceptionKiosk.js
MIN=../static/members/ReceptionKiosk.min.js

if elm-make --yes ${ELM} --output=${JS} && minify --output ${MIN} ${JS}

then
    sed -i "1i// Generated by Elm" ${JS}
    sed -i "1i// Generated by Elm" ${MIN}
fi
beep
